name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: fetch

    steps:
    - uses: actions/checkout@v4
    - name: print hostname
      run: hostname
    - name: build docker image
      run: docker build -t django:v${{ github.run_number }} .
    - name: docker image tag
      run: docker tag django:v iamkaushal20/deerwalk:v${{ github.run_number }}
    - name: docker login
      run: docker login -u ${{ vars.USERNAME }} -p ${{ vars.PASSWORD }}
    - name: docker push
      run: docker push iamkaushal20/deerwalk:v${{ github.run_number }}
  deploy:

    runs-on: deploy
    steps: 
    - name: pull docker image
      run: hostname