name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: fetch

    steps:
    - uses: actions/checkout@v4
    - name: print hostname
      run: hostname
    - name: build docker image
      run: docker build -t django:v${{ github.run_number }} .
    - name: docker image tag
      run: docker tag django:v${{ github.run_number }} iamkaushal20/deerwalk:v${{ github.run_number }}
    - name: docker login
      run: docker login -u ${{ vars.USERNAME }} -p ${{ secrets.PASSWORD1 }}
    - name: docker push
      run: docker push iamkaushal20/deerwalk:v${{ github.run_number }}
  deploy:
    needs: build
    runs-on: deploy
    steps: 
    - name: print hostname
      run: hostname
    # - name: stop container if exists
    #  run: docker container stop app
    # - name: delete container
      # run: docker container rm app
    - name: pull conimage and run container
      run: docker run --name app -p 9000:9000 -d iamkaushal20/deerwalk:v${{ github.run_number }}
