name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: feth

    steps:
    - uses: actions/checkout@v4
    - name: print hostname
      run: hostname

  deploy:

    runs-on: deploy
    steps: 
    - name: pull docker image
      run: hostname